### PR TITLE
feat: finals tracker api update

### PR DESCRIPTION
**Pull request by Swackles**
I updated the finals tracker API, old endpoint is getting deprecated and new one gives more customization.

Docs are publicly available [here](https://api.finals-tracker.com/api/swagger/)

### CODE REVIEW

**Comment by leonlarsson** [comment]
Thanks! I've noted some issues I spotted in the commit:

- User ProntoBlade#2322 on crossplay has cases where rank is displayed as 0 (null)
- Gazillion names returned, currently breaking UI: https://api.finals-tracker.com/api//v1/users?name=kuneboii&platform=playstation

**Comment by Swackles** [comment]
ProntoBlade#2322 is working as expected, he fell out of top 10k on crossplay between december 30th and january 5th and then also on january 6th. Cause he fell out of top 10k, no idea what his rank is and thus gets displayed as null.

Yes, there seems to be an issue with a lot of steam, xbox and playstation names. Going to fix it ASAP.

**Comment by leonlarsson** [comment]
Thanks for clarifying. I've set it to -10_000 so it shows low on the chart instead of high

**Comment by leonlarsson** [comment]
Closing for now. Hoping Embark adds consistent player IDs.

**Pull request closed without merging**
