### PR TITLE
feat: filters are now stored in uri

### PR DESCRIPTION
**Pull request by Swackles**
I changed how platform filtering looks like, making it more consistent with the overall ui. Platform, version and username filters are also now stored in uri.

### CODE REVIEW

**Comment by leonlarsson** [comment]
Thanks. I really dig these changes. I made some minor changes (nothing functional).

There is an issue that causes leaderboard version to reset on refresh.
I would also like to disable the platform picker if `live` isn't the selected version.

**Comment by Swackles** [comment]
Yup, those changes make sense

**Comment by leonlarsson** [comment]
I'm seeing a lot of input lag when typing into the name filter

**Comment by leonlarsson** [comment]
Putting the URL state on hold for now, but I'll add the new platform selection design in a new commit to main.

**Comment by Swackles** [comment]
Personally, didn't see a performance hit on my machine, but it is highly likely that this issue is caused by `useLayoutEffect`. Try changing it to `useEffect` and see if the problem persists.

**Comment by leonlarsson** [comment]
I did try that and other changes, but unfortunately didn't see any performance gains.

**Comment by Swackles** [comment]
That is unfortunate, it's my pet peeve when sites don't store query information in the path.

One alternative could be to add an artificial timeout period. So let's say that filter changes made within 3s are all grouped together into one larger update.

**Comment by leonlarsson** [comment]
I agree, I'm also a big fan of using the URL as state. I'll keep looking into it (and why this one was so laggy for me).
I don't see why it would lag though

**Comment by leonlarsson** [comment]
I've implemented a first functional draft of storing the state in the URL in the main branch. For whatever reason, this runs much more performant for me. I will likely revisit this later to polish it up.

**Pull request closed without merging**
