### PR TITLE
feat: show rank and fame history

### PR DESCRIPTION
**Pull request by Swackles**
This is a small thing I've been working on in the background.

API that has daily snapshots of the in-game leaderboard and makes it possible to query that data. I would like to add this as a feature to the leaderboard and asking for your permission.

This is not final yet, there are still a few bugs and issues to work out before I can merge it.

### CODE REVIEW

**Comment by leonlarsson** [comment]
Some things that will need fixing:

- ~Chart needs to be updated to also support dark mode~ (fixed in https://github.com/leonlarsson/the-finals-leaderboard/pull/11/commits/df519603903d931c259380ee4d46fdedadeefe6a)
- ~All rows should un-expand when the leaderboard version or platform is changed~ (fixed in https://github.com/leonlarsson/the-finals-leaderboard/pull/11/commits/baac47ab1d1fbaaf95c9900981db0d181b6afd90)
- When hovering the chart points: `Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

**Comment by Swackles** [comment]
I take it that you like this feature :)

I will today fix the API and then it's pretty much ready.

The big issue is with steam, xbox and ps leaderboards where usernames are not unique and thus and the backend mat hes multiple users to the namr. I'm currently thinking that if there are multiple users, the user selects the matching user and query data based on that.

Another future addition could be a mixed leaderbaord, where there are around additional 10k leaderboard entries.

**Comment by leonlarsson** [comment]
I do like the idea :)

And yeah, the big blocker is the lack of consistent identifiers

**Comment by Swackles** [comment]
There is still a lot that could be done with this, but I think for now it's ready to go.

### Changes

1. Reworked the backend API where it returns all the users that have a matching name and now the client can select between those users himself. (This can be seen with the `@Arkaik__ on twitch` on the [steam](https://the-finals-leaderboard.com/?platform=steam) leaderboard.

2. Added loading feedback to the client so there isn't an awkward pause between click and data being shown, with that also added MUI as a dependency as `radix-ui` does not provide a clean loading bar.

3. Renamed `theme` to `selectedTheme` inside `ThemeProvider` as the name theme implies it's a collection of attributes that the app uses, while it really meant the currently active mode.

4. Moved Mui theme provider into the `ThemeProvider`, we shouldn't generate it 20 separate times.


### Change proposals

I saw that you added years to graph dates. I personally think that they should be removed or the very least shortened. The reason for this is that the dates themselves should add enough context about the year and with a larger amount of graph data it could become obstructed.

**Comment by leonlarsson** [comment]
I've gone ahead and made toggling the expanded row a bit more clear by adding a new column with a button.

On the date thing, I do prefer at least some display of which year it is, especially as we are just a day from 2024. Once we have more data, I can change the year to be 2-digit.

But this now looks good to me.

Thanks for the implementation :)

**Comment by leonlarsson** [comment]
I see that I broke the LinearProgress by fixing not being able to close.
Fixed in https://github.com/leonlarsson/the-finals-leaderboard/commit/94fcba68f83d82b54d2b1864d5e4fe132f44ec42

**Pull request merged**
